app:
  kafka:
    bootstrap:
      server: localhost:9092
    request:
      timeout:
        ms: 60000
    compresion:
      type: gzip
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 200
      heartbeat-interval: 7000
      session-timeout-ms: 30000
      max-poll-interval-ms: 600000
      fetch-max-wait-ms: 5000
      fetch-min-bytes: 40000
      listener:
        concurrency: 1
        poll-timeout: 600000
      errorHandler:
        intervalMs: 1000
        maxRetries: 2
      simpleConsumer:
        group-id: java-application-1
        topic:
          name: first_java_topic

